# Generated by Django 4.2.24 on 2025-10-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userrole_unique_together_remove_userrole_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_path',
            field=models.FileField(blank=True, null=True, upload_to='image_profile/'),
        ),
    ]
