# Generated by Django 4.2.24 on 2025-10-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('accounts', '0003_alter_user_profile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='blogs.blog'),
        ),
    ]
