# Generated by Django 4.2.24 on 2025-10-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to='image_post/'),
        ),
    ]
