# Generated by Django 4.2.24 on 2025-10-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bookmarked_posts'),
        ('blogs', '0004_alter_blog_body'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogReport',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=200)),
                ('action_taken', models.CharField(choices=[('private', 'Private'), ('delete', 'Delete')], max_length=20)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.blog')),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_handled', to='accounts.user')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_reported', to='accounts.user')),
            ],
        ),
    ]
