# Generated by Django 4.2.24 on 2025-10-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_body'),
        ('reports', '0002_logreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportblog',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.comment'),
        ),
    ]
